### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by paxperscientiam** [rejas/imagelightbox#119]
hey @rejas @GenaBitu , etc,

I'm resurrecting this thread in attempt to aggregate all the ideas that we've been bouncing around. My thinking is that if we can put together a sort of "roadmap", it'll ensure that development of `imagelightbox` moves forward in a coherent fashion.

If you guys are down, just tell me what to add/tweak. Maybe it would be a good idea to finish this first before merging non-critical stuff?

What is a "lightbox"?
In short, it's a [modal window](https://en.wikipedia.org/wiki/Modal_window) with the background content "darkened" or obscured.

Broad questions to answer, according to [Nielson Norman Group](https://www.nngroup.com/articles/overuse-of-overlays/).

PRINCIPLES
===

- **Who** is the target audience?
Developers with graphical content to share, allowing for supplemental text
- **What** action is the user supposed to take?
...
- **When** will the overlay appear, and will it be an interruption?
`imagelightbox` is not built to annoy.
- Where will the overlay appear on the page?
...

**Scope:**
- 

GOALS
===

**Features**
- [ ] matrix (static)
- [ ] matrix (rubiks)

**Structure/logic:** see PR #163 #184 
- [ ] Adopt "dependency injection" concept. For instance, inferring the state of the image from any give point in the code is a nightmare due to the `image` variable's large scope.
- [ ] Improve handling of image loading. #22 #178 #176 

**Performance**
- [ ] Make better.

**Accessibility**
- [ ] Adheres to ...

**i18n** PR  ; issue #129
- [ ] Follows semiotic standards / best practices.

**Compatibility** see #183 #180 
- [ ]

**Maintainability**
- [ ] Auto document #106

**Comment by rejas** [comment]
Hi pax, no vision from my side, I was waiting for pull requests from you :-) The history feature you dont plan on following up on again?

**Comment by paxperscientiam** [comment]
> The history feature you dont plan on following up on again?

I do.

**Comment by rejas** [comment]
Could you open a new issue for this? Recycling issues is confusing when old comments are still there....
